version: '3'
services:
  stashdbsyncer:
    container_name: stashdb-syncer
    build:
      context: ./
    image: stashdb-syncer:latest  
    environment:
      - DEBUG=True
    ports:
      - "5000:5000"
